### ISSUE TITLE
AutoExplore not working after 3 days

### ISSUE THREAD

**Issue by InnohVateur** [InnohVateur/RandomMoons#1]
So when you leave and there 0 days left, but the quota is met, it wont travel to a random moon cuz im dumb. Already fixed, just need to upload it, it will come tomorrow as the 1.2.1 release.

**Comment by Dust29** [comment]
The worst kinds of bug are the small bugs

-Someone wise, probably

**Comment by InnohVateur** [comment]
> The worst kinds of bug are the small bugs
> 
> -Someone wise, probably

I eat small bugs
