### ISSUE TITLE
Can you update CSync to 4.1.0

### ISSUE THREAD

**Issue by 1410677474** [InnohVateur/RandomMoons#3]

**Comment by Dust29** [comment]
As stated above in #4, I'm gonna try to upgrade the mod by the end of the week. Sorry for the delay.

**Comment by Dust29** [comment]
Hello, the mod has been updated to V50 on ThunderStore
Configuration is still not working, but you can now use the mod in v50 relatively bug free.

**Comment by Dust29** [comment]
Update : The update is well under way, and should release around wenesday
