### ISSUE TITLE
Can you update CSync to 5.0.0 

### ISSUE THREAD

**Issue by 1410677474** [InnohVateur/RandomMoons#4]
I really like this module, but the v50 doesn't work

**Comment by Dust29** [comment]
Hi, this is dust, a friend of InnohVateur. He dosen't want to work on the mod anymore, at least not for a while. However, I'm going to work on it on his behalf. If I dont run into too many trouble, you can except a working version out by the end of the week. I'l keep you posted. And please don't hesistate to suggest anything we could add to upgrade the moon !

**Comment by 1410677474** [comment]
> Hi, this is dust, a friend of InnohVateur. He dosen't want to work on the mod anymore, at least not for a while. However, I'm going to work on it on his behalf. If I dont run into too many trouble, you can except a working version out by the end of the week. I'l keep you posted. And please don't hesistate to suggest anything we could add to upgrade the moon !

Using csync3.1.1 in the v50 version resulted in a low frame count for the host

thx bro

**Comment by Dust29** [comment]
Noted, I'l see what I can do.

I have a question : Did someone else try to host and ran into the same fps drop issue ?

**Comment by 1410677474** [comment]
> Noted, I'l see what I can do.
> 
> I have a question : Did someone else try to host and ran into the same fps drop issue ?

yes,It is normal to remove this module, sometimes this module does not have the normal random resulting low frame count, and now I only need a version that can be used in v50, I will test it

**Comment by Dust29** [comment]
I'm not sure that I understood your comment, sorry.

**Comment by 1410677474** [comment]
> Did someone else try to host and ran into the same fps drop issue
 Yes

**Comment by Dust29** [comment]
Update : I have a working v50 version of the mod, without lethal config nor Csync

**Comment by Dust29** [comment]
The update is now on thunderstore. There may be bugs, but I think it should work fine in V50. 
But, right now the only way to change the config is via R2Modman GUI. Sorry for the inconveniance, I will fix that ASAP

**Comment by 1410677474** [comment]
> The update is now on thunderstore. There may be bugs, but I think it should work fine in V50. But, right now the only way to change the config is via R2Modman GUI. Sorry for the inconveniance, I will fix that ASAP

Thx bro for your work

**Comment by Dust29** [comment]
You'r welcome ! Enjoy you time with the mod, and don't hesistate to report any bug you may encounter while playing !
And as always, if you have idea for improvement, feel free to share them as well !

**Comment by Dust29** [comment]
Update : Lethal Config and Lethal Settings are working again, however I can't get Csync to well sync the config just yet for some reason. I will add all of the settings and see if it's works, and either way I will make a release out of that !

**Comment by Dust29** [comment]
Update : With the help of @Owen3H , the creator of Csync, We were able (Well he was able to be honest) to fix the issue. Now I need to add all of the config that I want to be fixed and to test all of em. This will take a day or two, you can except 1.3.1 to release on thunderstore around wensday.
